import fs from "node:fs";
import path from "node:path";
import { cache } from "react";
import type { Metadata } from "next";

/**
 * IRCTC standard class/zone catering menus (Rajdhani/premium 1AC-EC, AC
 * 2A-3A-CC, Duronto sleeper). Data generated by scripts/ingest-standard-menus.ts
 * and committed under content/standard-menu/<classgroup>-<zone>.json. Rendered
 * by the standard-menu pages under /irctc-train-food-menu/<slug>.
 */

export type StandardService = {
  service: string;
  price: number | null;
  sets: string[];
};

export type StandardZoneMenu = {
  zone: string;
  key: string;
  services: StandardService[];
  sourcePdfUrl: string;
};

export type StandardMenuGroup = {
  classGroup: string;
  classGroupName: string;
  slug: string;
  covers: string;
  zones: StandardZoneMenu[];
};

const DIR = path.join(process.cwd(), "content", "standard-menu");

/** One page per class group. Static segments under /irctc-train-food-menu/. */
export const STANDARD_MENU_PAGES = [
  {
    slug: "rajdhani-1ac-executive",
    classGroup: "1AC-EC",
    classGroupName: "AC First Class & Executive Chair Car",
    covers: "Rajdhani and premium trains, First AC (1A) and Executive Chair Car (EC)",
    heading: "Rajdhani (1AC & Executive Chair Car) Food Menu",
    // CTR title (≤48 ch so it survives "%s | LastBerth"): keyword + question
    // hook. Rajdhani catering is bundled into the fare, so "What's Included?"
    // is both a hook and truthful to the page.
    metaTitle: "Rajdhani Food Menu & Price: What's Included?",
  },
  {
    slug: "ac-2a-3a-cc",
    classGroup: "2A-3A-CC",
    classGroupName: "AC 2-Tier, 3-Tier & Chair Car",
    covers: "Rajdhani, Shatabdi and AC Mail/Express, in AC 2-Tier (2A), 3-Tier (3A) and Chair Car (CC)",
    heading: "AC 2A / 3A / Chair Car Food Menu",
    metaTitle: "AC 2A/3A/Chair Car Food Menu & Meal Prices",
  },
  {
    slug: "duronto-sleeper",
    classGroup: "duronto-sleeper",
    classGroupName: "Duronto Sleeper Class",
    covers: "Duronto Express trains, sleeper class",
    heading: "Duronto Sleeper Class Food Menu",
    metaTitle: "Duronto Food Menu & Price: What's Included?",
  },
] as const;

const ZONE_ORDER = [
  "North",
  "East",
  "West",
  "South",
  "South Central",
  "Jain Meal",
  "Diabetic Meal",
  "Continental Menu",
];

type RawMenu = StandardZoneMenu & { classGroup: string; classGroupName: string };

function readAll(): RawMenu[] {
  if (!fs.existsSync(DIR)) return [];
  const out: RawMenu[] = [];
  for (const f of fs.readdirSync(DIR)) {
    if (!f.endsWith(".json")) continue;
    try {
      out.push(JSON.parse(fs.readFileSync(path.join(DIR, f), "utf8")) as RawMenu);
    } catch {
      /* skip bad file */
    }
  }
  return out;
}

export const getStandardMenuGroup = cache(
  (slug: string): StandardMenuGroup | null => {
    const cfg = STANDARD_MENU_PAGES.find((p) => p.slug === slug);
    if (!cfg) return null;
    const zones = readAll()
      .filter((m) => m.classGroup === cfg.classGroup)
      .map((m) => ({
        zone: m.zone,
        key: m.key,
        services: m.services,
        sourcePdfUrl: m.sourcePdfUrl,
      }))
      .sort(
        (a, b) =>
          (ZONE_ORDER.indexOf(a.zone) + 1 || 99) -
          (ZONE_ORDER.indexOf(b.zone) + 1 || 99),
      );
    if (zones.length === 0) return null;
    return {
      classGroup: cfg.classGroup,
      classGroupName: cfg.classGroupName,
      slug: cfg.slug,
      covers: cfg.covers,
      zones,
    };
  },
);

export function listStandardMenuSlugs(): string[] {
  return STANDARD_MENU_PAGES.filter((p) => getStandardMenuGroup(p.slug)).map(
    (p) => p.slug,
  );
}

/** Metadata for a standard-menu page (title deduped: layout adds "| LastBerth"). */
export function standardMenuMetadata(slug: string): Metadata {
  const cfg = STANDARD_MENU_PAGES.find((p) => p.slug === slug);
  const group = getStandardMenuGroup(slug);
  if (!cfg || !group) return { title: "Train Food Menu" };
  const prices = group.zones
    .flatMap((z) => z.services.map((s) => s.price))
    .filter((p): p is number => typeof p === "number");
  const min = prices.length ? Math.min(...prices) : null;
  const description = `IRCTC food menu and catering prices for ${cfg.classGroupName} on ${cfg.covers}. Morning tea, breakfast, lunch, dinner and snacks with per-meal charges by zone${
    min != null ? `, starting at ₹${min}` : ""
  }, inclusive of taxes.`;
  return {
    title: cfg.metaTitle,
    description,
    keywords: [
      `${cfg.classGroupName} food menu`,
      `rajdhani food menu price`,
      `duronto food menu`,
      `irctc ${cfg.slug} menu`,
      `train meal price ${cfg.classGroup}`,
    ],
    alternates: { canonical: `/irctc-train-food-menu/${cfg.slug}` },
    openGraph: { title: cfg.metaTitle, description },
  };
}
